// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.4.0
// - protoc             v3.19.4
// source: goods.proto

package goods

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.62.0 or later.
const _ = grpc.SupportPackageIsVersion8

const (
	GoodsSrv_AddOrder_FullMethodName  = "/proto.GoodsSrv/AddOrder"
	GoodsSrv_OrderList_FullMethodName = "/proto.GoodsSrv/OrderList"
)

// GoodsSrvClient is the client API for GoodsSrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoodsSrvClient interface {
	AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error)
	OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error)
}

type goodsSrvClient struct {
	cc grpc.ClientConnInterface
}

func NewGoodsSrvClient(cc grpc.ClientConnInterface) GoodsSrvClient {
	return &goodsSrvClient{cc}
}

func (c *goodsSrvClient) AddOrder(ctx context.Context, in *AddOrderRequest, opts ...grpc.CallOption) (*AddOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddOrderResponse)
	err := c.cc.Invoke(ctx, GoodsSrv_AddOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *goodsSrvClient) OrderList(ctx context.Context, in *OrderListRequest, opts ...grpc.CallOption) (*OrderListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(OrderListResponse)
	err := c.cc.Invoke(ctx, GoodsSrv_OrderList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsSrvServer is the server API for GoodsSrv service.
// All implementations must embed UnimplementedGoodsSrvServer
// for forward compatibility
type GoodsSrvServer interface {
	AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error)
	OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error)
	mustEmbedUnimplementedGoodsSrvServer()
}

// UnimplementedGoodsSrvServer must be embedded to have forward compatible implementations.
type UnimplementedGoodsSrvServer struct {
}

func (UnimplementedGoodsSrvServer) AddOrder(context.Context, *AddOrderRequest) (*AddOrderResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddOrder not implemented")
}
func (UnimplementedGoodsSrvServer) OrderList(context.Context, *OrderListRequest) (*OrderListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OrderList not implemented")
}
func (UnimplementedGoodsSrvServer) mustEmbedUnimplementedGoodsSrvServer() {}

// UnsafeGoodsSrvServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoodsSrvServer will
// result in compilation errors.
type UnsafeGoodsSrvServer interface {
	mustEmbedUnimplementedGoodsSrvServer()
}

func RegisterGoodsSrvServer(s grpc.ServiceRegistrar, srv GoodsSrvServer) {
	s.RegisterService(&GoodsSrv_ServiceDesc, srv)
}

func _GoodsSrv_AddOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSrvServer).AddOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsSrv_AddOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSrvServer).AddOrder(ctx, req.(*AddOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GoodsSrv_OrderList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OrderListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsSrvServer).OrderList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoodsSrv_OrderList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsSrvServer).OrderList(ctx, req.(*OrderListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GoodsSrv_ServiceDesc is the grpc.ServiceDesc for GoodsSrv service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoodsSrv_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GoodsSrv",
	HandlerType: (*GoodsSrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddOrder",
			Handler:    _GoodsSrv_AddOrder_Handler,
		},
		{
			MethodName: "OrderList",
			Handler:    _GoodsSrv_OrderList_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
