name: 部署后端项目到 MinIO
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-minio:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 安装 MinIO 客户端（使用有效下载链接）
      - name: 安装 MinIO 客户端
        run: |
          # 使用官方最新稳定版链接（确保存在）
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          
          # 验证客户端版本
          ./mc --version
          
          # 配置连接
          ./mc alias set myminio http://14.103.235.216:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
        continue-on-error: false

      # 3. 同步文件到 MinIO
      - name: 同步项目文件到 MinIO
        run: |
          # 验证连接
          ./mc ls myminio
          
          # 基础同步命令（仅保留兼容参数）
          ./mc cp -r --force ./ myminio/mybucket/
        continue-on-error: false
    
