name: 部署微服务（修正目录路径）
on:
  push:
    branches: [ main ]

jobs:
  deploy-microservices:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取最新代码
        uses: actions/checkout@v4

      # 显示项目目录结构（用于调试路径问题）
      - name: 查看项目目录结构
        run: |
          echo "当前项目根目录文件列表："
          ls -la
          echo "子目录列表："
          find . -maxdepth 2 -type d  # 加深层级查看，适配实际目录

      # 编译 api-gateway 服务
      - name: 编译 api-gateway 服务
        run: |
          API_DIR="./api-gateway/basic/cmd"  # 定位到 main.go 所在目录
          echo "检查 API 服务目录: $API_DIR"
          if [ ! -d "$API_DIR" ]; then
            echo "错误: API 服务目录 $API_DIR 不存在"
            exit 1
          fi
          
          cd "$API_DIR"
          go mod tidy  # 基于 api-gateway 下的 go.mod 处理依赖
          go build -o api-service main.go
          zip -r ../../../api-deploy.zip api-service  # 回到根目录打包

      # 编译 goods-server 服务
      - name: 编译 goods-server 服务
        run: |
          SERVER_DIR="./goods-server/basic/cmd"  # 定位到 main.go 所在目录
          echo "检查 Server 服务目录: $SERVER_DIR"
          if [ ! -d "$SERVER_DIR" ]; then
            echo "错误: Server 服务目录 $SERVER_DIR 不存在"
            exit 1
          fi
          
          cd "$SERVER_DIR"
          go mod tidy  # 基于 goods-server 下的 go.mod 处理依赖
          go build -o server-service main.go
          zip -r ../../../server-deploy.zip server-service  # 回到根目录打包

      # 部署到服务器
      - name: 部署到服务器
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_SSH_PORT || 22 }}
          script: |
            BASE_PATH="/opt/microservices"
            mkdir -p $BASE_PATH/{api,server,config}
            
            # 部署配置文件（假设 dev.yaml 在项目根目录）
            cd $BASE_PATH/config
            cp ${{ github.workspace }}/dev.yaml $BASE_PATH/config/
            chmod 644 $BASE_PATH/config/dev.yaml
            
            # 部署 server 服务
            cd $BASE_PATH/server
            cp ${{ github.workspace }}/server-deploy.zip $BASE_PATH/server/
            unzip -o server-deploy.zip
            chmod +x server-service
            pkill -f "server-service" || true
            sleep 2
            nohup ./server-service --config $BASE_PATH/config/dev.yaml > server.log 2>&1 &
            
            # 等待 server 启动
            for i in {1..15}; do
              if pgrep -f "server-service" > /dev/null && nc -z localhost 8081; then
                echo "server 服务已就绪"
                break
              fi
              sleep 2
            done
            
            # 部署 api 服务
            cd $BASE_PATH/api
            cp ${{ github.workspace }}/api-deploy.zip $BASE_PATH/api/
            unzip -o api-deploy.zip
            chmod +x api-service
            pkill -f "api-service" || true
            sleep 2
            nohup ./api-service --config $BASE_PATH/config/dev.yaml > api.log 2>&1 &
            
            # 验证服务
            sleep 3
            if pgrep -f "server-service" && pgrep -f "api-service"; then
              echo "所有服务启动成功"
            else
              cat $BASE_PATH/server/server.log
              cat $BASE_PATH/api/api.log
              exit 1
            fi
