name: 部署后端项目到 MinIO
on:
  push:
    branches: [ main ]  # 推送 main 分支触发
jobs:
  deploy-to-minio:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 安装 MinIO 客户端（mc）
      - name: 安装 MinIO 客户端
        run: |
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          # 配置 MinIO 连接（使用 API 端口 9000）
          ./mc config host add myminio http://14.103.235.216:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
        continue-on-error: false  # 连接失败终止流程

      # 3. 验证 MinIO 连接并同步项目文件
      - name: 同步项目文件到 MinIO
        run: |
          # 验证连接是否正常
          ./mc ls myminio
          
          # 同步所有项目文件到 MinIO 的 mybucket 存储桶
          # 排除不需要上传的文件（如 .git、node_modules 等）
          ./mc cp -r -f \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            ./ myminio/mybucket/
        continue-on-error: false  # 同步失败终止流程
    
