name: 部署后端项目到 MinIO
on:
  push:
    branches: [ main ]
jobs:
  deploy-to-minio:
    runs-on: ubuntu-latest
    steps:
      # 1. 拉取代码
      - name: 拉取代码
        uses: actions/checkout@v4

      # 2. 安装 MinIO 客户端（mc）并配置连接
      - name: 安装 MinIO 客户端并配置连接
        run: |
          # 下载 mc 客户端
          wget https://dl.min.io/client/mc/release/linux-amd64/mc
          chmod +x mc
          
          # 关键修正：使用 alias 命令替代 config 命令（兼容旧版本）
          ./mc alias set myminio http://14.103.235.216:9000 ${{ secrets.MINIO_ACCESS_KEY }} ${{ secrets.MINIO_SECRET_KEY }}
        continue-on-error: false

      # 3. 验证连接并同步文件
      - name: 同步项目文件到 MinIO
        run: |
          # 验证连接是否成功
          ./mc ls myminio
          
          # 同步文件到存储桶
          ./mc cp -r -f \
            --exclude ".git/" \
            --exclude ".github/" \
            ./ myminio/mybucket/
        continue-on-error: false
    
